#
# Build stage
#
FROM maven:3.6.0-jdk-8-slim AS build
COPY ./vendas/src /home/app/src
COPY ./vendas/pom.xml /home/app
RUN mvn -Dmaven.repo.local=/.m2 -f /home/app/pom.xml package -Dmaven.test.skip=true

#
# Package stage
#
FROM openjdk:8-jre-slim
COPY --from=build /home/app/target/vendas-0.0.1-SNAPSHOT.jar /usr/local/lib/vendas.jar
ENV TZ 'America/Fortaleza'
RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get install -y tzdata && \
    apt-get install -y fontconfig libfreetype6 && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean
ENTRYPOINT ["java","-jar","/usr/local/lib/vendas.jar"]
